---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermicroservice2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: usermicroservice2
    spec:
      containers:
        - name: usermicroservice
          image: kousiksen09/usermicroservice:djdinesh
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: usermicroservice2
---
apiVersion: v1
kind: Service
metadata:
  name: usermicroservice2
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: usermicroservice2
