version: '3.4'

services:
  tweetappapigateway:
    image: ${DOCKER_REGISTRY-}debs21/tweetappapigateway:dev
    build:
      context: .
      dockerfile: TweetAppAPIGateway/Dockerfile
    links:
      - tweetpostmicroservice
      - usermicroservice
      - tweetview_replymicroservice
    depends_on:
      - tweetpostmicroservice
      - usermicroservice
      - tweetview_replymicroservice

  tweetpostmicroservice:
    image: ${DOCKER_REGISTRY-}debs21/tweetpostmicroservice:dev
    container_name: TweetPostMicroservice
    hostname: tweetpostmicroservice
    build:
      context: .
      dockerfile: TweetPOSTMicroservice/Dockerfile


  tweetview_replymicroservice:
    image: ${DOCKER_REGISTRY-}debs21/tweetviewreplymicroservice:dev
    container_name: TweetView_ReplyMicroservice
    hostname: tweetview_replymicroservice
    build:
      context: .
      dockerfile: TweetView_ReplyMicroservice/Dockerfile


  usermicroservice:
    image: ${DOCKER_REGISTRY-}debs21/usermicroservice:dev
    container_name: UserMicroservice
    hostname: usermicroservice
    build:
      context: .
      dockerfile: UserMicroservice/Dockerfile

  tweetdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
    - SA_PASSWORD=2Secure*Password2
    - ACCEPT_EULA=Y
    ports:
    - "1450:1433"
    
