version: '3.4'
services:
  usermicroservice:
    image: ${DOCKER_REGISTRY-}usermicroservice
    build:
      context: .
      dockerfile: UserMicroservice/Dockerfile
    depends_on:
        - "sqldb"

  tweetpostmicroservice:
    image: ${DOCKER_REGISTRY-}tweetpostmicroservice
    build:
      context: .
      dockerfile: TweetPOSTMicroservice/Dockerfile
    depends_on:
        - "sqldb"


  tweetview_replymicroservice:
    image: ${DOCKER_REGISTRY-}tweetviewreplymicroservice
    build:
      context: .
      dockerfile: TweetView_ReplyMicroservice/Dockerfile
    depends_on:
        - "sqldb"
  tweetappapigateway:
    image: ${DOCKER_REGISTRY-}tweetappapigateway
    build:
      context: .
      dockerfile: TweetAppAPIGateway/Dockerfile
    links:
      - tweetpostmicroservice
      - usermicroservice
      - tweetview_replymicroservice
    depends_on:
      - tweetpostmicroservice
      - usermicroservice
      - tweetview_replymicroservice
  
  sqldb:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
        SA_PASSWORD: "Password@123"
        ACCEPT_EULA: "Y"
    ports:
        - "1440:1433"   




