version: '3.4'

services:
  tweetpostmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5500:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  usermicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5501:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  tweetview_replymicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5502:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  tweetappapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5503:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
