export const REGISTER_API_FETCH_INITIATED = 'REGISTER_API_FETCH_INITIATED';
export const REGISTER_API_FETCH_SUCCESS = 'REGISTER_API_FETCH_SUCCESS';
export const REGISTER_API_FETCH_ERROR = 'REGISTER_API_FETCH_ERROR';

export const LOGIN_API_FETCH_INITIATED = 'LOGIN_API_FETCH_INITIATED';
export const LOGIN_API_FETCH_SUCCESS = 'LOGIN_API_FETCH_SUCCESS';
export const LOGIN_API_FETCH_ERROR = 'LOGIN_API_FETCH_ERROR';

export const PROFILE_API_FETCH_INITIATED = 'PROFILE_API_FETCH_INITIATED';
export const PROFILE_API_FETCH_SUCCESS = 'PROFILE_API_FETCH_SUCCESS';
export const PROFILE_API_FETCH_ERROR = 'PROFILE_API_FETCH_ERROR';

export const FINDUSERNAME_API_FETCH_INITIATED =
    'FINDUSERNAME_API_FETCH_INITIATED';
export const FINDUSERNAME_API_FETCH_SUCCESS = 'FINDUSERNAME_API_FETCH_SUCCESS';
export const FINDUSERNAME_API_FETCH_ERROR = 'FINDUSERNAME_API_FETCH_ERROR';

export const GETALLUSER_API_FETCH_INITIATED = 'GETALLUSER_API_FETCH_INITIATED';
export const GETALLUSER_API_FETCH_SUCCESS = 'GETALLUSER_API_FETCH_SUCCESS';
export const GETALLUSER_API_FETCH_ERROR = 'GETALLUSER_API_FETCH_ERROR';

export const GETALLTWEET_API_FETCH_INITIATED =
  'GETALLTWEET_API_FETCH_INITIATED';
export const GETALLTWEET_API_FETCH_SUCCESS = 'GETALLTWEET_API_FETCH_SUCCESS';
export const GETALLTWEET_API_FETCH_ERROR = 'GETALLTWEET_API_FETCH_ERROR';
export const POST_API_FETCH_INITIATED = 'POST_API_FETCH_INITIATED';
export const POST_API_FETCH_SUCCESS = 'POST_API_FETCH_SUCCESS';
export const POST_API_FETCH_ERROR = 'POST_API_FETCH_ERROR';

export const LIKE_API_FETCH_INITIATED = 'LIKE_API_FETCH_INITIATED';
export const LIKE_API_FETCH_SUCCESS = 'LIKE_API_FETCH_SUCCESS';
export const LIKE_API_FETCH_ERROR = 'LIKE_API_FETCH_ERROR';

export const TWEETREPLY_API_FETCH_INITIATED = 'TWEETREPLY_API_FETCH_INITIATED';
export const TWEETREPLY_API_FETCH_SUCCESS = 'TWEETREPLY_API_FETCH_SUCCESS';
export const TWEETREPLY_API_FETCH_ERROR = 'TWEETREPLY_API_FETCH_ERROR';

