export const REGISTER_API_FETCH_INITIATED = 'REGISTER_API_FETCH_INITIATED';
export const REGISTER_API_FETCH_SUCCESS = 'REGISTER_API_FETCH_SUCCESS';
export const REGISTER_API_FETCH_ERROR = 'REGISTER_API_FETCH_ERROR';

export const LOGIN_API_FETCH_INITIATED = 'LOGIN_API_FETCH_INITIATED';
export const LOGIN_API_FETCH_SUCCESS = 'LOGIN_API_FETCH_SUCCESS';
export const LOGIN_API_FETCH_ERROR = 'LOGIN_API_FETCH_ERROR';

export const POST_API_FETCH_INITIATED = 'POST_API_FETCH_INITIATED';
export const POST_API_FETCH_SUCCESS = 'POST_API_FETCH_SUCCESS';
export const POST_API_FETCH_ERROR = 'POST_API_FETCH_ERROR';
