---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twtweetpostmicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: twtweetpostmicroservice
    spec:
      containers:
        - name: twtweetpostmicroservice
          image: debasreec/tweetpostmicroservice:djdinesh
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: twtweetpostmicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: twtweetpostmicroservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: twtweetpostmicroservice
