---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetapigateway2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweetapigateway2
    spec:
      containers:
        - name: tweetapigateway2
          image: debasreec/tweetappapigateway:ocelot
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: tweetapigateway2
---
apiVersion: v1
kind: Service
metadata:
  name: tweetapigateway2
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: tweetapigateway2
