---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twtweetreplymicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: twtweetreplymicroservice
    spec:
      containers:
        - name: twtweetreplymicroservice
          image: debasreec/tweetviewreplymicroservice:djdinesh
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: twtweetreplymicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: twtweetreplymicroservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: twtweetreplymicroservice
