---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetreplymicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweetreplymicroservice
    spec:
      containers:
        - name: tweetreplymicroservice
          image: debasreec/tweetviewreplymicroservice:djdinesh
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: tweetreplymicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: tweetreplymicroservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: tweetreplymicroservice
